server:
  port: 8181

spring:
  application:
    name: keycloak-admin

dh:
  keycloak:
    serverUrl: http://localhost:8080
    realm: el-aparato-trodriguez
    clientId: rest-admin-client
    clientSecret: fP8cw984pf9i5AgMfNiygcBJLc5Clewz
